## DATBASE ##
DATABASE_IP = "127.0.0.1"
DATABASE_USER = "root"
DATABASE_PASSWORD = ""
DATBASE_NAME = "ecole"

## OTHERS ##
STRING_MAX_SIZE = 255
STRING_MIDLE_SIZE = 200
STRING_LITTLE_SIZE = 50
STRING_TEL_SIZE = 13