DATABASE_PROVIDER = "mysql"
DATABASE_HOST = "localhost"
DATABASE_USER = "root"
DATABASE_PASS = ""
DATABASE_NAME = "ecole"

SESSION_KEY_LENGTH = 24

## OTHERS ##
STRING_MAX_SIZE = 255
STRING_MIDLE_SIZE = 200
STRING_LITTLE_SIZE = 50
STRING_TEL_SIZE = 13